package com.transferlan.plus;
import android.app.*;import android.os.*;import android.content.*;import android.net.*;import android.provider.*;import android.database.*;import android.view.*;import android.widget.*;import android.graphics.*;import java.io.*;import java.net.*;import java.util.*;

public class MainActivity extends Activity{
 static final int PICK=1201; EditText urlInput; TextView status; LinearLayout devices; Uri selected;
 public void onCreate(Bundle b){super.onCreate(b); ui(); shared(getIntent());}
 public void onNewIntent(Intent i){super.onNewIntent(i); shared(i);}
 void ui(){ScrollView s=new ScrollView(this); LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); l.setPadding(32,48,32,32); l.setBackgroundColor(Color.rgb(15,23,42));
 TextView t=txt("TransferLAN+",28,229,231,235), sub=txt("Sin cuentas. Sin nube. Sin cables.",15,56,189,248); l.addView(t);l.addView(sub);
 Button scan=new Button(this); scan.setText("Buscar dispositivos"); scan.setOnClickListener(v->scan()); l.addView(scan);
 devices=new LinearLayout(this); devices.setOrientation(LinearLayout.VERTICAL); l.addView(devices);
 urlInput=new EditText(this); urlInput.setHint("http://IP-DE-TU-PC:5050"); urlInput.setText("http://"); urlInput.setSingleLine(true); urlInput.setTextColor(Color.WHITE); urlInput.setHintTextColor(Color.GRAY); l.addView(urlInput);
 Button pick=new Button(this); pick.setText("Elegir archivo"); pick.setOnClickListener(v->pick()); l.addView(pick);
 Button send=new Button(this); send.setText("Enviar a la PC"); send.setOnClickListener(v->send()); l.addView(send);
 status=txt("Esperando archivo...",15,229,231,235); status.setPadding(0,24,0,0); l.addView(status); s.addView(l); setContentView(s);}
 TextView txt(String x,int sz,int r,int g,int b){TextView v=new TextView(this);v.setText(x);v.setTextSize(sz);v.setTextColor(Color.rgb(r,g,b));return v;}
 void shared(Intent i){ if(i!=null&&Intent.ACTION_SEND.equals(i.getAction())){Uri u=i.getParcelableExtra(Intent.EXTRA_STREAM); if(u!=null){selected=u; if(status!=null)status.setText("Archivo compartido: "+name(u));}}}
 void scan(){devices.removeAllViews(); status.setText("Buscando..."); new Thread(()->{String ip=local(); if(ip.length()==0){runOnUiThread(()->status.setText("No se detectó IP local"));return;} String pre=ip.substring(0,ip.lastIndexOf(".")+1); int[] f={0}; for(int i=1;i<=254;i++){String base="http://"+pre+i+":5050"; try{HttpURLConnection c=(HttpURLConnection)new URL(base+"/device/info").openConnection();c.setConnectTimeout(180);c.setReadTimeout(250); if(c.getResponseCode()==200){String body=read(c.getInputStream());f[0]++; runOnUiThread(()->addDevice(base,body));}c.disconnect();}catch(Exception e){}} runOnUiThread(()->status.setText(f[0]==0?"No se encontraron dispositivos":("Dispositivos encontrados: "+f[0])));}).start();}
 void addDevice(String base,String info){Button b=new Button(this);b.setText("Usar "+base);b.setOnClickListener(v->{urlInput.setText(base);status.setText("Destino: "+base);});devices.addView(b);TextView d=txt(info,11,148,163,184);devices.addView(d);}
 String local(){try{Enumeration<NetworkInterface> es=NetworkInterface.getNetworkInterfaces();while(es.hasMoreElements()){NetworkInterface n=es.nextElement();Enumeration<InetAddress> as=n.getInetAddresses();while(as.hasMoreElements()){InetAddress a=as.nextElement();if(!a.isLoopbackAddress()&&a instanceof java.net.Inet4Address)return a.getHostAddress();}}}catch(Exception e){}return "";}
 String read(InputStream in)throws Exception{BufferedReader br=new BufferedReader(new InputStreamReader(in));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line).append("\n");return sb.toString();}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){selected=d.getData();status.setText("Seleccionado: "+name(selected));}}
 void send(){if(selected==null){toast("Primero elegí archivo");return;}String base=urlInput.getText().toString().trim();while(base.endsWith("/"))base=base.substring(0,base.length()-1);if(!base.startsWith("http")){toast("URL inválida");return;}String fb=base;status.setText("Enviando...");new Thread(()->{try{upload(fb,selected);runOnUiThread(()->status.setText("Archivo enviado correctamente"));}catch(Exception e){runOnUiThread(()->status.setText("Error: "+e.getMessage()));}}).start();}
 void upload(String base,Uri uri)throws Exception{String bd="TL"+System.currentTimeMillis();HttpURLConnection c=(HttpURLConnection)new URL(base+"/transfer/upload").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","multipart/form-data; boundary="+bd);InputStream in=getContentResolver().openInputStream(uri);DataOutputStream out=new DataOutputStream(c.getOutputStream());String fn=name(uri);out.writeBytes("--"+bd+"\r\nContent-Disposition: form-data; name=\"file\"; filename=\""+fn+"\"\r\nContent-Type: application/octet-stream\r\n\r\n");byte[] buf=new byte[262144];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();out.writeBytes("\r\n--"+bd+"--\r\n");out.close();int code=c.getResponseCode();if(code<200||code>299)throw new Exception("HTTP "+code);}
 String name(Uri u){String n="archivo_transferlan";Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){try{int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0&&c.moveToFirst())n=c.getString(i);}finally{c.close();}}return n;}
 void toast(String m){Toast.makeText(this,m,Toast.LENGTH_SHORT).show();}
}
